"""
Phase 4 · Lesson 5 — Structured Agents
Tools with complex structured inputs using Pydantic

WHAT WE ARE TRYING TO ACHIEVE:
Previous lessons → tools with simple string inputs
Structured agents → tools with multiple typed fields
Real world: database queries, report generation, API calls need structured inputs
"""

from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.tools import tool, StructuredTool
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from pydantic import BaseModel, Field
import json
import os

load_dotenv()

llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0, max_tokens=500)

# ── Setup RAG ─────────────────────────────────────────────────
print("Setting up...")
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
faiss_store = FAISS.load_local(
    "Phase2/faiss_index",
    embeddings,
    allow_dangerous_deserialization=True
)
retriever = faiss_store.as_retriever(search_kwargs={"k": 3})
print("✅ Ready!")
print()


# ── 1. Structured Tool with Pydantic ─────────────────────────
# Define exact input schema using Pydantic BaseModel
# LLM sees these fields and fills them correctly

class DocumentSearchInput(BaseModel):
    question: str = Field(description="The question to search for in the document")
    page_filter: int = Field(default=-1, description="Filter by page number. Use -1 for all pages")
    max_results: int = Field(default=3, description="Maximum number of results to return (1-5)")

class CalculationInput(BaseModel):
    expression: str = Field(description="Math expression to evaluate e.g. '150 * 0.15'")
    round_to: int = Field(default=2, description="Decimal places to round result to")

class ReportInput(BaseModel):
    title: str = Field(description="Title of the report")
    findings: str = Field(description="Key findings to include in report")
    recommendation: str = Field(description="Recommendations based on findings")
    format: str = Field(default="brief", description="Report format: 'brief' or 'detailed'")


# ── 2. Define structured tools ────────────────────────────────

def _search_document(question: str, page_filter: int = -1, max_results: int = 3) -> str:
    """Search document with optional page filtering"""
    docs = retriever.invoke(question)

    if page_filter != -1:
        docs = [d for d in docs if d.metadata.get('page') == page_filter]

    docs = docs[:max_results]

    if not docs:
        return "No results found"

    results = []
    for doc in docs:
        page = doc.metadata.get('page', 'N/A')
        results.append(f"[Page {page}]: {doc.page_content[:250]}")
    return "\n\n".join(results)


def _calculate(expression: str, round_to: int = 2) -> str:
    """Calculate with rounding"""
    try:
        expression = expression.strip().strip("{}")
        result = eval(expression)
        return str(round(float(result), round_to))
    except Exception as e:
        return f"Error: {e}"


def _generate_report(title: str, findings: str, recommendation: str, format: str = "brief") -> str:
    """Generate a structured report"""
    if format == "brief":
        return f"""
REPORT: {title}
{'='*40}
FINDINGS: {findings}
RECOMMENDATION: {recommendation}
"""
    else:
        return f"""
{'='*40}
DETAILED REPORT
{'='*40}
Title: {title}

KEY FINDINGS:
{findings}

RECOMMENDATIONS:
{recommendation}

Generated by AI Research Assistant
{'='*40}
"""


# Create structured tools
search_tool = StructuredTool.from_function(
    func=_search_document,
    name="search_document",
    description="Search the UPI research document. Use page_filter to search specific pages.",
    args_schema=DocumentSearchInput,
)

calc_tool = StructuredTool.from_function(
    func=_calculate,
    name="calculate",
    description="Perform math calculations with optional rounding.",
    args_schema=CalculationInput,
)

report_tool = StructuredTool.from_function(
    func=_generate_report,
    name="generate_report",
    description="Generate a structured report with title, findings, and recommendations.",
    args_schema=ReportInput,
)

tools = [search_tool, calc_tool, report_tool]

print("=== Structured Tools ===")
for t in tools:
    print(f"Tool: {t.name}")
    print(f"  Schema: {list(t.args_schema.model_fields.keys())}")
print()


# ── 3. Agent with structured tools ───────────────────────────
prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a research assistant with access to structured tools.
Use tools with precise inputs to find and analyze information.
Always generate a final report summarizing your findings."""),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}"),
    MessagesPlaceholder("agent_scratchpad"),
])

agent = create_tool_calling_agent(llm, tools, prompt)
executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    max_iterations=6,
    handle_parsing_errors=True,
)


# ── 4. Run structured agent ───────────────────────────────────
print("="*55)
print("=== Structured Agent in Action ===")
print("="*55)

result = executor.invoke({
    "input": """Research the UPI study and create a brief report:
    1. Find the sample size
    2. Calculate 10% of sample size
    3. Generate a report with your findings""",
    "chat_history": [],
})

print(f"\nFinal Output:\n{result['output']}")

print("""
=== Simple vs Structured Tools ===

Simple tool:
  def search(query: str) -> str
  → one input, no validation

Structured tool:
  class SearchInput(BaseModel):
      question: str
      page_filter: int
      max_results: int
  → multiple typed inputs, validated by Pydantic

When to use structured tools:
  → Tool needs multiple inputs
  → Inputs need type validation
  → Tool is complex like report generation or DB queries
  → You want LLM to fill specific fields precisely
""")